---
version: 2.1

parameters:
    run_workflow_deploy:
        type: boolean
        default: true

std-filters: &std-filters
    filters:
        branches:
            ignore:
            - devel
            - tmp
        tags:
            only: /.*/

- run: echo << pipeline.parameters.trigger-string >> | tee -a output.txt
      - store_artifacts:
          path: ./output.txt
          destination: output.txt

workflows:
    build_all:
        jobs:

## ----------------------android, mac, jammy commented out 28/07/24
        - build-debian-arm64-12-bookworm:
            <<: *std-filters
        - build-debian-armhf-12-bookworm:
            <<: *std-filters
        - build-debian-x86_64-12-bookworm:
            <<: *std-filters
        - build-debian-armhf-11-bullseye:
            <<: *std-filters
        - build-debian-arm64-11-bullseye:
            <<: *std-filters
        - build-debian-x86_64-11-bullseye:
            <<: *std-filters
orbs:
    cloudsmith: cloudsmith/cloudsmith@1.0.5
   ## win: circleci/windows@5.0

commands:
    deploy-code:
        parameters:
            install-python:
                type: boolean
                default: false
            DEPLOY-USE-ORB:
                type: boolean
                default: true
        steps:
            - when:
                condition: <<pipeline.parameters.run_workflow_deploy>>
                steps:
                - when:
                    condition: <<parameters.install-python>>
                    steps:
                    - run: sudo apt install -y python3-pip
                    - run: python3 -m pip install cloudsmith-cli
                - when:
                    condition: <<parameters.DEPLOY-USE-ORB>>
                    steps:
                    - cloudsmith/ensure-api-key
                    - cloudsmith/install-cli
                - run: bash ci/cloudsmith-upload.sh

    # if you want to use a local proxy add Acquire::http::Proxy \"http://192.168.1.1:3142\"; to a file called circleci-cache/apt-proxy. This will require
    #    --volume {your local directory}/circleci-cache:/home/circleci/circleci-cache
    # on the circleci local command line so that the docker image script can have access to the directory
    # if you are on a slow or data limited internet link you can put a copy of master.zip here, or allow one to be downloaded by the script, as it is used by the android builds to
    # provide the wxWidgets QT information.

jobs:
## ---------------------
## OpenCPN 5.8 Plugins
## ---------------------
    build-debian-arm64-12-bookworm:
        machine:
            image: ubuntu-2004:202104-01
        environment:
        - OCPN_TARGET=bookworm-arm64
        - DOCKER_IMAGE=arm64v8/debian:bookworm
        - BUILD_FLAGS=-j3
        - BUILD_ENV=debian
        - WX_VER: 32
        - BUILD_GTK3: true
        - DEPLOY_USE_ORB: true
        steps:
        - checkout
        - run: chmod a+x ./ci/*.sh
        - run:
            command: ci/circleci-build-ubuntu-docker.sh
            no_output_timeout: 30m
        - deploy-code
    build-debian-armhf-12-bookworm:
        machine:
            image: ubuntu-2004:202104-01
        resource_class: arm.medium
        environment:
        - OCPN_TARGET=bookworm-armhf
        - DOCKER_IMAGE=arm32v7/debian:bookworm
        - BUILD_FLAGS=-j3
        - BUILD_ENV=debian
        - WX_VER: 32
        - BUILD_GTK3: true
        - DEPLOY_USE_ORB: true
        steps:
        - checkout
        - run: chmod a+x ./ci/*.sh
        - run:
            command: ci/circleci-build-ubuntu-docker.sh
            no_output_timeout: 30m
        - deploy-code
    build-debian-x86_64-12-bookworm:
        machine:
            image: ubuntu-2004:202104-01
        environment:
        - OCPN_TARGET: bookworm
        - BUILD_GTK3: true
        - WX_VER: 32
        - DEPLOY_USE_ORB: true
        - BUILD_ENV=debian
        - DOCKER_IMAGE=debian:bookworm
        steps:
        - checkout
        - run: chmod a+x ci/*.sh
        - run:
            command: ci/circleci-build-ubuntu-docker.sh
            no_output_timeout: 30m
        - deploy-code
    build-debian-armhf-11-bullseye:
        machine:
            image: ubuntu-2004:202104-01
        environment:
        - OCPN_TARGET=bullseye-armhf
        - DOCKER_IMAGE=jongough/debian-armhf:bullseye
        - BUILD_FLAGS=-j3
        - BUILD_ENV=debian
        - BUILD_GTK3: true
        - DEPLOY_USE_ORB: true
        steps:
        - checkout
        - run: chmod a+x ./ci/*.sh
        - run:
            command: ci/circleci-build-ubuntu-docker.sh
            no_output_timeout: 30m
        - deploy-code
    build-debian-arm64-11-bullseye:
        machine:
            image: ubuntu-2004:202104-01
        environment:
        - OCPN_TARGET=bullseye-arm64
        - DOCKER_IMAGE=arm64v8/debian:bullseye-backports
        - BUILD_FLAGS=-j3
        - BUILD_ENV=debian
        - BUILD_GTK3: true
        - DEPLOY_USE_ORB: true
        steps:
        - checkout
        - run: chmod a+x ./ci/*.sh
        - run:
            command: ci/circleci-build-ubuntu-docker.sh
            no_output_timeout: 30m
        - deploy-code
    build-debian-x86_64-11-bullseye:
        docker:
        - image: circleci/buildpack-deps:bullseye-scm
        environment:
        - OCPN_TARGET:  bullseye
        - BUILD_GTK3: true
        - DEPLOY_USE_ORB: true
        - BUILD_ENV=debian
        steps:
        - checkout
        - run: >
            echo "deb-src http://ftp.us.debian.org/debian bullseye main"
            | sudo tee -a /etc/apt/sources.list
        - run: >
            echo "deb-src http://ftp.us.debian.org/debian bullseye-updates main"
            | sudo tee -a /etc/apt/sources.list
        - run: cat /etc/apt/sources.list
        - run: chmod a+x ci/*.sh
        - run: ci/circleci-build-debian.sh
        - deploy-code
